import { useEffect, useState } from "react"
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, Legend } from "recharts"
import { API, FundRow, Flow, FundDetail, Overview, getFunds, getFund, getFlows, getOverview } from "./api"

type Tab = "overview" | "funds" | "yields" | "flows"

const fmtUsd = (n: number) => {
  if (n >= 1e9) return `$${(n / 1e9).toFixed(2)}B`
  if (n >= 1e6) return `$${(n / 1e6).toFixed(1)}M`
  return `$${n.toLocaleString()}`
}

const fmtPct = (n: number | null | undefined) =>
  n === null || n === undefined ? "—" : `${n > 0 ? "+" : ""}${n.toFixed(2)}%`

const fmtTime = (iso: string) => {
  const d = new Date(iso)
  if (isNaN(d.getTime())) return iso
  return d.toLocaleString("en-GB", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" })
}

function Structured({ text }: { text: string | null }) {
  if (!text) return null
  const lines = text
    .replace(/\\n/g, "\n")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
  return (
    <div className="narr">
      {lines.map((l, i) => {
        const m = l.match(/^([^:]{2,24}):\s?(.*)$/)
        if (!m) return <p key={i}>{l}</p>
        const watch = m[1].toLowerCase().includes("watch")
        return (
          <p key={i} className={watch ? "watch" : ""}>
            <b>{m[1]}:</b> {m[2]}
          </p>
        )
      })}
    </div>
  )
}

function Chips({ funds }: { funds: FundRow[] }) {
  const total = funds.reduce((a, f) => a + f.tvl, 0)
  const top = [...funds].filter((f) => f.yield > 0).sort((a, b) => b.yield - a.yield)[0]
  const gainer = [...funds].filter((f) => f.chg_7d_pct != null).sort((a, b) => b.chg_7d_pct - a.chg_7d_pct)[0]
  return (
    <div className="chips">
      <div className="chip">
        <b>{fmtUsd(total)}</b>
        <span>Total TVL · {funds.length} funds</span>
      </div>
      <div className="chip">
        <b>{top ? `${top.yield.toFixed(2)}%` : "—"}</b>
        <span>Top yield · {top?.ticker ?? ""}</span>
      </div>
      <div className="chip">
        <b className={gainer && gainer.chg_7d_pct >= 0 ? "pos" : "neg"}>{gainer ? fmtPct(gainer.chg_7d_pct) : "—"}</b>
        <span>Best 7d · {gainer?.ticker ?? ""}</span>
      </div>
    </div>
  )
}

const badge = (action: string) => <span className={`badge ${action}`}>{action}</span>

function OverviewView({ ov, funds }: { ov: Overview; funds: FundRow[] }) {
  const m = ov.macro
  const order = { BUY: 0, HOLD: 1, SELL: 2 } as Record<string, number>
  const sigs = [...ov.signals].sort(
    (a, b) => (order[a.action] ?? 9) - (order[b.action] ?? 9) || a.ticker.localeCompare(b.ticker),
  )
  return (
    <div>
      <div className="agent">
        <h2>🤖 Analyst view — {ov.date}</h2>
        <p>{ov.market_view}</p>
        <div className="meta">
          Updated {fmtTime(ov.generated_at)} · generated by the EuroRWA analyst agent · every report is hashed &amp;
          signed on-chain ({ov.signer.slice(0, 10)}…{ov.signer.slice(-4)}) · hash {ov.hash.slice(0, 12)}…
        </div>
      </div>

      <Chips funds={funds} />

      <div className="chips">
        <div className="chip">
          <b>{m.fear_greed.value}</b>
          <span>Fear &amp; Greed · {m.fear_greed.label}</span>
        </div>
        <div className="chip">
          <b>{m.tbill_yield.toFixed(2)}%</b>
          <span>US T-bill</span>
        </div>
        <div className="chip">
          <b>{m.max_rwa_yield.toFixed(2)}%</b>
          <span>Top RWA yield</span>
        </div>
        <div className="chip">
          <b className={m.spread >= 0 ? "pos" : "neg"}>{fmtPct(m.spread)}</b>
          <span>RWA vs T-bill spread</span>
        </div>
      </div>

      {ov.crypto && (
        <div className="agent">
          <h2>🪙 Crypto market</h2>
          <Structured text={ov.crypto_view} />
          <div className="chips">
            <div className="chip">
              <b>{fmtUsd(ov.crypto.mcap.usd)}</b>
              <span className={ov.crypto.mcap.chg_24h_pct >= 0 ? "pos" : "neg"}>
                Mkt cap {fmtPct(ov.crypto.mcap.chg_24h_pct)}
              </span>
            </div>
            <div className="chip">
              <b>{fmtUsd(ov.crypto.volume.usd)}</b>
              <span>24h volume</span>
            </div>
            <div className="chip">
              <b>{fmtUsd(ov.crypto.btc.usd)}</b>
              <span className={ov.crypto.btc.chg_24h >= 0 ? "pos" : "neg"}>BTC {fmtPct(ov.crypto.btc.chg_24h)}</span>
            </div>
            <div className="chip">
              <b>{fmtUsd(ov.crypto.eth.usd)}</b>
              <span className={ov.crypto.eth.chg_24h >= 0 ? "pos" : "neg"}>ETH {fmtPct(ov.crypto.eth.chg_24h)}</span>
            </div>
            <div className="chip">
              <b>{ov.crypto.dominance.btc.toFixed(1)}%</b>
              <span>BTC dominance</span>
            </div>
            <div className="chip">
              <b>{ov.crypto.dominance.eth.toFixed(1)}%</b>
              <span>ETH dominance</span>
            </div>
          </div>
          {(ov.crypto.movers.gainers.length || ov.crypto.movers.losers.length) && (
            <div className="meta">
              {ov.crypto.movers.gainers.length > 0 && (
                <span>Top: {ov.crypto.movers.gainers.map((g) => `${g.sym} ${fmtPct(g.pct)}`).join(" · ")}</span>
              )}
              {ov.crypto.movers.losers.length > 0 && (
                <span> · Flop: {ov.crypto.movers.losers.map((g) => `${g.sym} ${fmtPct(g.pct)}`).join(" · ")}</span>
              )}
            </div>
          )}
          {ov.crypto.trending.length > 0 && <div className="meta">🔥 Trending: {ov.crypto.trending.join(" · ")}</div>}
        </div>
      )}

      {ov.chain && (
        <div className="agent">
          <h2>⛓️ On-chain / Blockchain</h2>
          <Structured text={ov.chain_view} />
          <div className="chips">
            <div className="chip">
              <b>{fmtUsd(ov.chain.defi.tvl_usd)}</b>
              <span>DeFi TVL</span>
            </div>
            <div className="chip">
              <b>{fmtUsd(ov.chain.defi.stables_usd)}</b>
              <span className={ov.chain.defi.stables_chg_24h_pct >= 0 ? "pos" : "neg"}>
                Stablecoins {fmtPct(ov.chain.defi.stables_chg_24h_pct)}
              </span>
            </div>
            <div className="chip">
              <b>${ov.chain.btc.avg_fee_usd.toFixed(2)}</b>
              <span>BTC fee / tx</span>
            </div>
            <div className="chip">
              <b>{ov.chain.btc.tx_24h.toLocaleString()}</b>
              <span>BTC tx / 24h</span>
            </div>
            <div className="chip">
              <b>{ov.chain.eth.tx_24h.toLocaleString()}</b>
              <span>ETH tx / 24h</span>
            </div>
          </div>
          {ov.chain.defi.top.length > 0 && (
            <div className="meta">
              Top chains: {ov.chain.defi.top.map((t) => `${t.name} ${fmtUsd(t.tvl)}`).join(" · ")}
            </div>
          )}
        </div>
      )}

      <div className="sig-list">
        {sigs.map((s) => (
          <div className="sig" key={s.ticker}>
            <div className="sig-head">
              <span className="ticker">{s.ticker}</span>
              {badge(s.action)}
              <span className="conf">{s.confidence} confidence</span>
            </div>
            <ul>
              {s.reasons.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  )
}

function Table({ rows }: { rows: FundRow[] }) {
  return (
    <table>
      <thead>
        <tr>
          <th>Ticker</th>
          <th>Fund</th>
          <th>TVL</th>
          <th>7d</th>
          <th>APY</th>
          <th>Holders</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((r) => (
          <tr key={r.slug}>
            <td className="ticker">{r.ticker}</td>
            <td>{r.name}</td>
            <td>{fmtUsd(r.tvl)}</td>
            <td className={r.chg_7d_pct >= 0 ? "pos" : "neg"}>{fmtPct(r.chg_7d_pct)}</td>
            <td>{r.yield > 0 ? `${r.yield.toFixed(2)}%` : "—"}</td>
            <td>{r.holders || "—"}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

function Detail({ slug, onClose }: { slug: string; onClose: () => void }) {
  const [d, setD] = useState<FundDetail | null>(null)
  useEffect(() => {
    getFund(slug)
      .then(setD)
      .catch(() => setD(null))
  }, [slug])
  if (!d) return <div className="panel">loading…</div>
  const last = d.history[d.history.length - 1]
  return (
    <div className="panel">
      <div className="panel-head">
        <h2>
          {d.fund.ticker} — {d.fund.name}
        </h2>
        <button onClick={onClose}>×</button>
      </div>
      {last && (
        <div className="stats">
          <div>
            TVL <b>{fmtUsd(last.tvl)}</b>
          </div>
          <div>
            APY <b>{last.yield > 0 ? `${last.yield.toFixed(2)}%` : "—"}</b>
          </div>
          <div>
            7d <b className={last.chg_7d_pct >= 0 ? "pos" : "neg"}>{fmtPct(last.chg_7d_pct)}</b>
          </div>
          <div>
            Holders <b>{last.holders || "—"}</b>
          </div>
        </div>
      )}
      <div className="chart">
        <ResponsiveContainer width="100%" height={260}>
          <LineChart data={d.history}>
            <XAxis dataKey="date" />
            <YAxis yAxisId="l" />
            <YAxis yAxisId="r" orientation="right" />
            <Tooltip />
            <Legend />
            <Line yAxisId="l" type="monotone" dataKey="tvl" stroke="#2563eb" />
            <Line yAxisId="r" type="monotone" dataKey="yield" stroke="#16a34a" />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  )
}

function Yields({ rows }: { rows: FundRow[] }) {
  const list = [...rows].filter((r) => r.yield > 0).sort((a, b) => b.yield - a.yield)
  const max = list[0]?.yield ?? 1
  return (
    <div className="bars">
      {list.map((r) => (
        <div className="bar-row" key={r.slug}>
          <span className="bar-label">
            {r.ticker} <i>{fmtUsd(r.tvl)}</i>
          </span>
          <div className="bar-track">
            <div className="bar-fill" style={{ width: `${(r.yield / max) * 100}%` }} />
          </div>
          <span className="bar-val">{r.yield.toFixed(2)}%</span>
        </div>
      ))}
    </div>
  )
}

function Flows({ rows }: { rows: Flow[] }) {
  const list = [...rows].sort((a, b) => (b.flow ?? 0) - (a.flow ?? 0))
  return (
    <table>
      <thead>
        <tr>
          <th>Ticker</th>
          <th>TVL</th>
          <th>Net flow (24h)</th>
          <th>7d</th>
        </tr>
      </thead>
      <tbody>
        {list.map((r) => (
          <tr key={r.slug}>
            <td className="ticker">{r.ticker}</td>
            <td>{fmtUsd(r.tvl)}</td>
            <td className={r.flow != null && r.flow >= 0 ? "pos" : "neg"}>{r.flow == null ? "—" : fmtUsd(r.flow)}</td>
            <td className={r.chg_7d_pct >= 0 ? "pos" : "neg"}>{fmtPct(r.chg_7d_pct)}</td>
          </tr>
        ))}
      </tbody>
    </table>
  )
}

export default function App() {
  const [tab, setTab] = useState<Tab>("overview")
  const [funds, setFunds] = useState<FundRow[] | null>(null)
  const [flows, setFlows] = useState<Flow[] | null>(null)
  const [ov, setOv] = useState<Overview | null>(null)
  const [err, setErr] = useState("")
  const [slug, setSlug] = useState<string | null>(null)

  useEffect(() => {
    getFunds()
      .then((b) => setFunds(b.funds))
      .catch((e) => setErr(String(e)))
  }, [])
  useEffect(() => {
    if (tab === "flows")
      getFlows()
        .then((b) => setFlows(b.flows))
        .catch((e) => setErr(String(e)))
  }, [tab])
  useEffect(() => {
    if (tab === "overview")
      getOverview()
        .then(setOv)
        .catch(() => setOv(null))
  }, [tab])

  return (
    <main>
      <header>
        <div className="brand">
          <svg viewBox="0 0 200 200" width="36" height="36" aria-hidden="true">
            <defs>
              <linearGradient id="mark-g" x1="0" y1="0" x2="1" y2="1">
                <stop offset="0%" stopColor="#34d399" />
                <stop offset="100%" stopColor="#22d3ee" />
              </linearGradient>
            </defs>
            <circle cx="100" cy="100" r="13" fill="url(#mark-g)" />
            <circle cx="100" cy="100" r="5" fill="#0f172a" />
            {["162 100", "131 153.7", "69 153.7", "38 100", "69 46.3", "131 46.3"].map(([x, y]) => (
              <circle key={x + y} cx={x} cy={y} r="8" fill="#22d3ee" opacity="0.85" />
            ))}
            {[
              ["100 100", "131 153.7"],
              ["100 100", "69 153.7"],
              ["100 100", "38 100"],
              ["100 100", "69 46.3"],
              ["100 100", "131 46.3"],
            ].map(([a, b]) => (
              <line
                key={a + b}
                x1={a.split(" ")[0]}
                y1={a.split(" ")[1]}
                x2={b.split(" ")[0]}
                y2={b.split(" ")[1]}
                stroke="rgba(148,163,184,.5)"
                strokeWidth="3"
              />
            ))}
            {[
              ["162 100", "131 153.7"],
              ["131 153.7", "69 153.7"],
              ["69 153.7", "38 100"],
              ["38 100", "69 46.3"],
              ["69 46.3", "131 46.3"],
              ["131 46.3", "162 100"],
            ].map(([a, b]) => (
              <line
                key={a + b + "r"}
                x1={a.split(" ")[0]}
                y1={a.split(" ")[1]}
                x2={b.split(" ")[0]}
                y2={b.split(" ")[1]}
                stroke="rgba(52,211,153,.55)"
                strokeWidth="3"
              />
            ))}
          </svg>
          <h1>EuroRWA</h1>
        </div>
        <p>EU tokenized money market funds — data via rwa.xyz + on-chain, snapshotted daily.</p>
        <div className="tabs">
          {(["overview", "funds", "yields", "flows"] as Tab[]).map((t) => (
            <button key={t} className={tab === t ? "active" : ""} onClick={() => setTab(t)}>
              {t}
            </button>
          ))}
          <a className="tg" href="https://t.me/EuroRWA_Data_bot" target="_blank" rel="noreferrer">
            💬 Telegram
          </a>
        </div>
      </header>

      {err && (
        <div className="err">
          API unreachable at {API}: {err}
        </div>
      )}

      {tab === "overview" && (ov && funds ? <OverviewView ov={ov} funds={funds} /> : <p className="muted">loading…</p>)}

      {tab === "funds" &&
        (funds ? (
          <div
            onClick={(e) => {
              const row = (e.target as HTMLElement).closest("tr")
              const tk = row?.querySelector(".ticker")?.textContent
              if (tk) setSlug(tk.toLowerCase())
            }}
          >
            <Table rows={funds} />
            {slug && <Detail slug={slug} onClose={() => setSlug(null)} />}
          </div>
        ) : (
          <p className="muted">loading…</p>
        ))}

      {tab === "yields" && (funds ? <Yields rows={funds} /> : <p className="muted">loading…</p>)}

      {tab === "flows" && (flows ? <Flows rows={flows} /> : <p className="muted">loading…</p>)}
    </main>
  )
}
